version: '3.8'

services:
  auth_service:
    build: ./auth_service
    ports:
      - "5004:5000"
    environment:
      - FLASK_ENV=development

  user_service:
    build: ./user_service
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development

  bakery_service:
    build: ./bakery_service
    ports:
      - "5002:5000"
    environment:
      - FLASK_ENV=development

  backup_bakery_service:
    build: ./bakery_service
    ports:
      - "5003:5000"
    environment:
      - FLASK_ENV=development